apiVersion: v1
kind: Service
metadata:
  name: service1
  #namespace: kube-system
spec:
  selector:
    app: service1
  ports:
    - protocol: "TCP"
      port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  #namespace: kube-system
spec:
  selector:
    matchLabels:
      app: service1
  replicas: 2
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          image: service1:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: service2
  #namespace: kube-system
spec:
  selector:
    app: service2
  ports:
    - protocol: "TCP"
      port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
  #namespace: kube-system
spec:
  selector:
    matchLabels:
      app: service2
  replicas: 2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
        - name: service2
          image: service2:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: gw-service
  #namespace: kube-system
spec:
  selector:
    app: gw-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gw-app
  #namespace: kube-system
spec:
  selector:
    matchLabels:
      app: gw-app
  replicas: 2
  template:
    metadata:
      labels:
        app: gw-app
    spec:
      containers:
        - name: gw-app
          image: gwservice:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080